spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/user/**
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/product/**

server:
  port: 5000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka